version: '3.8'

services:
  ingestion_service:
    build: ../ingestion_service
    restart: always
    environment:
      - CONFIG_PATH=/config/config.yaml
    volumes:
      - ./config:/config
    networks:
      - anpr-net

  detection_service:
    build: ../detection_service
    restart: always
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - MODEL_PATH=/models/yolov8.pt
    volumes:
      - ../models:/models
    depends_on:
      - ingestion_service
    networks:
      - anpr-net

  ocr_service:
    build: ../ocr_service
    restart: always
    depends_on:
      - detection_service
    networks:
      - anpr-net

  tracking_service:
    build: ../tracking_service
    restart: always
    depends_on:
      - ocr_service
    networks:
      - anpr-net

  storage_service:
    build: ../storage_service
    restart: always
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/anpr
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioaccesskey
      - S3_SECRET_KEY=miniosecretkey
    depends_on:
      - db
      - minio
    networks:
      - anpr-net

  api_service:
    build: ../api_service
    restart: always
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/anpr
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - storage_service
      - redis
    ports:
      - "8000:8000"
    networks:
      - anpr-net

  dashboard:
    build: ../dashboard
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api_service
    networks:
      - anpr-net

  license_server:
    build: ../license_server
    restart: always
    networks:
      - anpr-net

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: anpr
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - anpr-net

  redis:
    image: redis:7
    restart: always
    networks:
      - anpr-net

  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ACCESS_KEY: minioaccesskey
      MINIO_SECRET_KEY: miniosecretkey
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - miniodata:/data
    networks:
      - anpr-net

networks:
  anpr-net:
    driver: bridge

volumes:
  pgdata:
  miniodata:
